packages:
  - backend
  - frontend

catalog:
  "@guillaume-docquier/tools-ts": ^6.3.1
  "@typescript/native-preview": 7.0.0-dev.20260707.2

minimumReleaseAgeExclude:
  - "@guillaume-docquier/tools-ts"

allowBuilds:
  "@clerk/shared": true
  bufferutil: true
  core-js: true
  cpu-features: false
  esbuild: true
  msw: true
  protobufjs: false
  ssh2: false
  utf-8-validate: true

peerDependencyRules:
  allowedVersions:
    # @clerk/ui ships with peer deps conflicts
    utf-8-validate: "6"

strictPeerDependencies: true
