packages:
  - backend
  - frontend
  - shared/*

catalog:
  "@guillaume-docquier/tools-ts": ^5.0.0

minimumReleaseAgeExclude:
  - "@guillaume-docquier/tools-ts"

allowBuilds:
  "@clerk/shared": true
  bufferutil: true
  core-js: true
  esbuild: true
  msw: true
  utf-8-validate: true
