# this is only used for dev, don't deploy this rofl
services:
  db:
    # Needs to be in sync with the load test image in loadTestHarness.ts
    image: postgres:18.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: cosmic-empires
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=cosmic-empires"]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - cosmic-empires-pgdata:/var/lib/postgresql

volumes:
  cosmic-empires-pgdata:
