/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/_game'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSignUpRouteImport } from './routes/_app.sign-up'
import { Route as AppSignInRouteImport } from './routes/_app.sign-in'
import { Route as AppGamesIndexRouteImport } from './routes/_app.games.index'
import { Route as AppGamesCreateRouteImport } from './routes/_app.games.create'
import { Route as AppGamesGameIdRouteImport } from './routes/_app.games.$gameId'
import { Route as GameGamesGameIdPlayRouteImport } from './routes/_game.games.$gameId.play'
import { Route as GameGamesGameIdPlayIndexRouteImport } from './routes/_game.games.$gameId.play.index'
import { Route as GameGamesGameIdPlayStarSystemRouteImport } from './routes/_game.games.$gameId.play.star-system'
import { Route as GameGamesGameIdPlayActionsRouteImport } from './routes/_game.games.$gameId.play.actions'

const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignUpRoute = AppSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInRoute = AppSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesCreateRoute = AppGamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameIdRoute = AppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const GameGamesGameIdPlayRoute = GameGamesGameIdPlayRouteImport.update({
  id: '/games/$gameId/play',
  path: '/games/$gameId/play',
  getParentRoute: () => GameRoute,
} as any)
const GameGamesGameIdPlayIndexRoute =
  GameGamesGameIdPlayIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)
const GameGamesGameIdPlayStarSystemRoute =
  GameGamesGameIdPlayStarSystemRouteImport.update({
    id: '/star-system',
    path: '/star-system',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)
const GameGamesGameIdPlayActionsRoute =
  GameGamesGameIdPlayActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppSignInRoute
  '/sign-up': typeof AppSignUpRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/create': typeof AppGamesCreateRoute
  '/games/': typeof AppGamesIndexRoute
  '/games/$gameId/play': typeof GameGamesGameIdPlayRouteWithChildren
  '/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/games/$gameId/play/': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppSignInRoute
  '/sign-up': typeof AppSignUpRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/create': typeof AppGamesCreateRoute
  '/games': typeof AppGamesIndexRoute
  '/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/games/$gameId/play': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_game': typeof GameRouteWithChildren
  '/_app/sign-in': typeof AppSignInRoute
  '/_app/sign-up': typeof AppSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/games/$gameId': typeof AppGamesGameIdRoute
  '/_app/games/create': typeof AppGamesCreateRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_game/games/$gameId/play': typeof GameGamesGameIdPlayRouteWithChildren
  '/_game/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/_game/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/_game/games/$gameId/play/': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/games/$gameId'
    | '/games/create'
    | '/games/'
    | '/games/$gameId/play'
    | '/games/$gameId/play/actions'
    | '/games/$gameId/play/star-system'
    | '/games/$gameId/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/games/$gameId'
    | '/games/create'
    | '/games'
    | '/games/$gameId/play/actions'
    | '/games/$gameId/play/star-system'
    | '/games/$gameId/play'
  id:
    | '__root__'
    | '/_app'
    | '/_game'
    | '/_app/sign-in'
    | '/_app/sign-up'
    | '/_app/'
    | '/_app/games/$gameId'
    | '/_app/games/create'
    | '/_app/games/'
    | '/_game/games/$gameId/play'
    | '/_game/games/$gameId/play/actions'
    | '/_game/games/$gameId/play/star-system'
    | '/_game/games/$gameId/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-up': {
      id: '/_app/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AppSignUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in': {
      id: '/_app/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppSignInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/create': {
      id: '/_app/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof AppGamesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameId': {
      id: '/_app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AppGamesGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_game/games/$gameId/play': {
      id: '/_game/games/$gameId/play'
      path: '/games/$gameId/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GameGamesGameIdPlayRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/games/$gameId/play/': {
      id: '/_game/games/$gameId/play/'
      path: '/'
      fullPath: '/games/$gameId/play/'
      preLoaderRoute: typeof GameGamesGameIdPlayIndexRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
    '/_game/games/$gameId/play/star-system': {
      id: '/_game/games/$gameId/play/star-system'
      path: '/star-system'
      fullPath: '/games/$gameId/play/star-system'
      preLoaderRoute: typeof GameGamesGameIdPlayStarSystemRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
    '/_game/games/$gameId/play/actions': {
      id: '/_game/games/$gameId/play/actions'
      path: '/actions'
      fullPath: '/games/$gameId/play/actions'
      preLoaderRoute: typeof GameGamesGameIdPlayActionsRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
  }
}

interface AppRouteChildren {
  AppSignInRoute: typeof AppSignInRoute
  AppSignUpRoute: typeof AppSignUpRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute
  AppGamesCreateRoute: typeof AppGamesCreateRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSignInRoute: AppSignInRoute,
  AppSignUpRoute: AppSignUpRoute,
  AppIndexRoute: AppIndexRoute,
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesCreateRoute: AppGamesCreateRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GameGamesGameIdPlayRouteChildren {
  GameGamesGameIdPlayActionsRoute: typeof GameGamesGameIdPlayActionsRoute
  GameGamesGameIdPlayStarSystemRoute: typeof GameGamesGameIdPlayStarSystemRoute
  GameGamesGameIdPlayIndexRoute: typeof GameGamesGameIdPlayIndexRoute
}

const GameGamesGameIdPlayRouteChildren: GameGamesGameIdPlayRouteChildren = {
  GameGamesGameIdPlayActionsRoute: GameGamesGameIdPlayActionsRoute,
  GameGamesGameIdPlayStarSystemRoute: GameGamesGameIdPlayStarSystemRoute,
  GameGamesGameIdPlayIndexRoute: GameGamesGameIdPlayIndexRoute,
}

const GameGamesGameIdPlayRouteWithChildren =
  GameGamesGameIdPlayRoute._addFileChildren(GameGamesGameIdPlayRouteChildren)

interface GameRouteChildren {
  GameGamesGameIdPlayRoute: typeof GameGamesGameIdPlayRouteWithChildren
}

const GameRouteChildren: GameRouteChildren = {
  GameGamesGameIdPlayRoute: GameGamesGameIdPlayRouteWithChildren,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
