/* oxlint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as GameRouteImport } from './routes/_game'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSignUpRouteImport } from './routes/_site.sign-up'
import { Route as SiteSignInRouteImport } from './routes/_site.sign-in'
import { Route as SiteGamesIndexRouteImport } from './routes/_site.games.index'
import { Route as SiteGamesCreateRouteImport } from './routes/_site.games.create'
import { Route as SiteGamesGameIdRouteImport } from './routes/_site.games.$gameId'
import { Route as GameGamesGameIdPlayRouteImport } from './routes/_game.games.$gameId.play'
import { Route as GameGamesGameIdPlayIndexRouteImport } from './routes/_game.games.$gameId.play.index'
import { Route as GameGamesGameIdPlayStarSystemRouteImport } from './routes/_game.games.$gameId.play.star-system'
import { Route as GameGamesGameIdPlayActionsRouteImport } from './routes/_game.games.$gameId.play.actions'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSignUpRoute = SiteSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSignInRoute = SiteSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamesIndexRoute = SiteGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamesCreateRoute = SiteGamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamesGameIdRoute = SiteGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => SiteRoute,
} as any)
const GameGamesGameIdPlayRoute = GameGamesGameIdPlayRouteImport.update({
  id: '/games/$gameId/play',
  path: '/games/$gameId/play',
  getParentRoute: () => GameRoute,
} as any)
const GameGamesGameIdPlayIndexRoute =
  GameGamesGameIdPlayIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)
const GameGamesGameIdPlayStarSystemRoute =
  GameGamesGameIdPlayStarSystemRouteImport.update({
    id: '/star-system',
    path: '/star-system',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)
const GameGamesGameIdPlayActionsRoute =
  GameGamesGameIdPlayActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => GameGamesGameIdPlayRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sign-in': typeof SiteSignInRoute
  '/sign-up': typeof SiteSignUpRoute
  '/games/$gameId': typeof SiteGamesGameIdRoute
  '/games/create': typeof SiteGamesCreateRoute
  '/games/': typeof SiteGamesIndexRoute
  '/games/$gameId/play': typeof GameGamesGameIdPlayRouteWithChildren
  '/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/games/$gameId/play/': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/sign-in': typeof SiteSignInRoute
  '/sign-up': typeof SiteSignUpRoute
  '/games/$gameId': typeof SiteGamesGameIdRoute
  '/games/create': typeof SiteGamesCreateRoute
  '/games': typeof SiteGamesIndexRoute
  '/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/games/$gameId/play': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_game': typeof GameRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_site/sign-in': typeof SiteSignInRoute
  '/_site/sign-up': typeof SiteSignUpRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/games/$gameId': typeof SiteGamesGameIdRoute
  '/_site/games/create': typeof SiteGamesCreateRoute
  '/_site/games/': typeof SiteGamesIndexRoute
  '/_game/games/$gameId/play': typeof GameGamesGameIdPlayRouteWithChildren
  '/_game/games/$gameId/play/actions': typeof GameGamesGameIdPlayActionsRoute
  '/_game/games/$gameId/play/star-system': typeof GameGamesGameIdPlayStarSystemRoute
  '/_game/games/$gameId/play/': typeof GameGamesGameIdPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/games/$gameId'
    | '/games/create'
    | '/games/'
    | '/games/$gameId/play'
    | '/games/$gameId/play/actions'
    | '/games/$gameId/play/star-system'
    | '/games/$gameId/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/games/$gameId'
    | '/games/create'
    | '/games'
    | '/games/$gameId/play/actions'
    | '/games/$gameId/play/star-system'
    | '/games/$gameId/play'
  id:
    | '__root__'
    | '/_game'
    | '/_site'
    | '/_site/sign-in'
    | '/_site/sign-up'
    | '/_site/'
    | '/_site/games/$gameId'
    | '/_site/games/create'
    | '/_site/games/'
    | '/_game/games/$gameId/play'
    | '/_game/games/$gameId/play/actions'
    | '/_game/games/$gameId/play/star-system'
    | '/_game/games/$gameId/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameRoute: typeof GameRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sign-up': {
      id: '/_site/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SiteSignUpRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sign-in': {
      id: '/_site/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SiteSignInRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/games/': {
      id: '/_site/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof SiteGamesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/games/create': {
      id: '/_site/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof SiteGamesCreateRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/games/$gameId': {
      id: '/_site/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof SiteGamesGameIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_game/games/$gameId/play': {
      id: '/_game/games/$gameId/play'
      path: '/games/$gameId/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GameGamesGameIdPlayRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/games/$gameId/play/': {
      id: '/_game/games/$gameId/play/'
      path: '/'
      fullPath: '/games/$gameId/play/'
      preLoaderRoute: typeof GameGamesGameIdPlayIndexRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
    '/_game/games/$gameId/play/star-system': {
      id: '/_game/games/$gameId/play/star-system'
      path: '/star-system'
      fullPath: '/games/$gameId/play/star-system'
      preLoaderRoute: typeof GameGamesGameIdPlayStarSystemRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
    '/_game/games/$gameId/play/actions': {
      id: '/_game/games/$gameId/play/actions'
      path: '/actions'
      fullPath: '/games/$gameId/play/actions'
      preLoaderRoute: typeof GameGamesGameIdPlayActionsRouteImport
      parentRoute: typeof GameGamesGameIdPlayRoute
    }
  }
}

interface GameGamesGameIdPlayRouteChildren {
  GameGamesGameIdPlayActionsRoute: typeof GameGamesGameIdPlayActionsRoute
  GameGamesGameIdPlayStarSystemRoute: typeof GameGamesGameIdPlayStarSystemRoute
  GameGamesGameIdPlayIndexRoute: typeof GameGamesGameIdPlayIndexRoute
}

const GameGamesGameIdPlayRouteChildren: GameGamesGameIdPlayRouteChildren = {
  GameGamesGameIdPlayActionsRoute: GameGamesGameIdPlayActionsRoute,
  GameGamesGameIdPlayStarSystemRoute: GameGamesGameIdPlayStarSystemRoute,
  GameGamesGameIdPlayIndexRoute: GameGamesGameIdPlayIndexRoute,
}

const GameGamesGameIdPlayRouteWithChildren =
  GameGamesGameIdPlayRoute._addFileChildren(GameGamesGameIdPlayRouteChildren)

interface GameRouteChildren {
  GameGamesGameIdPlayRoute: typeof GameGamesGameIdPlayRouteWithChildren
}

const GameRouteChildren: GameRouteChildren = {
  GameGamesGameIdPlayRoute: GameGamesGameIdPlayRouteWithChildren,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface SiteRouteChildren {
  SiteSignInRoute: typeof SiteSignInRoute
  SiteSignUpRoute: typeof SiteSignUpRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteGamesGameIdRoute: typeof SiteGamesGameIdRoute
  SiteGamesCreateRoute: typeof SiteGamesCreateRoute
  SiteGamesIndexRoute: typeof SiteGamesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSignInRoute: SiteSignInRoute,
  SiteSignUpRoute: SiteSignUpRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteGamesGameIdRoute: SiteGamesGameIdRoute,
  SiteGamesCreateRoute: SiteGamesCreateRoute,
  SiteGamesIndexRoute: SiteGamesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GameRoute: GameRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
