name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6

      - name: Setting up pnpm
        uses: pnpm/action-setup@v6

      - name: Setting up nodejs
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Frontend typecheck
        run: pnpm frontend:typecheck

      - name: Backend typecheck
        run: pnpm backend:typecheck

      - name: Backend tests with coverage
        run: pnpm backend:test:coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v6
        with:
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}
